### ISSUE TITLE
Path resolution issues.

### ISSUE THREAD

**Issue by giulioungaretti** [tk0miya/sphinxcontrib-jsonschema#1]
I think I may be doing something off but:

given this project structure, and this directive 

```
 .. jsonschema:: ../../qcodes/config/schema.json
```

<img width="231" alt="screenshot 2016-09-28 15 33 03" src="https://cloud.githubusercontent.com/assets/2694199/18915313/e135905a-8590-11e6-9687-e6766c8f16a3.png">

I get a file not found error. Tips ?

**Comment by elvijs** [comment]
I had the same issue. Not that it is a good solution, but using absolute paths does the job.

**Comment by tk0miya** [comment]
Thank you for reporting
I just released new package!
