### ISSUE TITLE
Arrays for "type"

### ISSUE THREAD

**Issue by janbrohl** [tk0miya/sphinxcontrib-jsonschema#3]
When trying to use your library with an array of allowed types like `"type":["string","null"]` I get `TypeError: unhashable type: 'list'` at https://github.com/tk0miya/sphinxcontrib-jsonschema/blob/e3b9136c07e804845b8efd0fb3beb217350c67c0/sphinxcontrib/jsonschema.py#L98
but I am quite sure this should be allowed according to [the spec](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.21)

You can see the Traceback at https://readthedocs.org/projects/scoutnet-apis/builds/4895113/
and my file at https://github.com/scoutnet/Docu-ScoutNet-APIs/blob/c9a35949875eb38d6521a5fcdb467c08a1f564e9/schemas/sn_rest/event.json

**Comment by tk0miya** [comment]
Ah, I don't know that specification...
As you said, jsonschema spec says `type` is either a string or an array.
>The value of this keyword MUST be either a string or an array. If it is an array, elements of the array MUST be strings and MUST be unique.
>http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.21

At this moment, it is not supported. My extension accepts only a string as type.
I'll take a look later.

Thank you for reporting

**Comment by janbrohl** [comment]
With #4 you would get minmal support for type-Arrays

**Comment by tk0miya** [comment]
I implemented it at bae8067.
Could you try this please?
I will release it if it works fine.

**Comment by janbrohl** [comment]
Works fine for me :)

Thank you!

**Comment by janbrohl** [comment]
Please release.

**Comment by tk0miya** [comment]
Just released
